name: iceveps2
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - xarray=0.19.0
  - geopandas=0.10.2
  - cartopy=0.20.2
  - cdo=2.0.5
  - python-cdo=1.5.6
  - regionmask=0.9.0
  - pcraster=4.3.3
  - netcdf4=1.5.8
  - pyomo==6.4.1
  - glpk=5.0
  - dask
